apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - application.yaml

# Optional: Add common labels to all resources
commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: workout-api
